development:
  domain: localhost:3000
  root: elthariel
  audio_root: /home/opp2/code/new_radio/data
  sox: /usr/bin/sox
  sox_nice: 19
  sox_format: --channels 2 --type vorbis -C 4
  sox_fx: gain -1 highpass 28 0.001q rate -v -a 44100 dither -s
  sox_fx_low: delay 0 0.005 reverb wet-gain -25
  ftp_root: /home/opp2/code/new_radio/upload
  ftp_id: 1000
  ftp_gid: 1000
  ftp_default_quota: 104857600
  ftp_sessions: 3

test:
  domain: test.host
  audio_root: /home/opp2/code/new_radio/data

production:
  domain: example.com
