development:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3

test:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3

production:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3
