development:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3
  logfile: log/scheduler_dev.log
  loglevel: DEBUG

test:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3
  logfile: log/scheduler_test.log
  loglevel: DEBUG

production:
  playlist_lookahead: 10
  liq_socket: ./radio.sock
  liq_queue: rq
  liq_live: live
  audiofile_metric_increment: 0.3
  logfile: log/scheduler_prod.log
  loglevel: DEBUG
